# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

project_name: gose

before:
  hooks:
  - go mod tidy
  - npm --prefix ./frontend install
  - npm --prefix ./frontend run-script build

builds:
  - env:
    - CGO_ENABLED=0

    main: ./cmd

    tags:
    - embed

    goos:
    - linux
    - windows
    - darwin

    goarch:
    - "386"
    - amd64
    - arm
    - arm64

    goarm:
    - "7"

archives:
- format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
- id: amd64
  image_templates: 
  - "ghcr.io/stv0g/gose:amd64-{{ .Tag }}"
  - "ghcr.io/stv0g/gose:amd64-v{{ .Major }}"
  - "ghcr.io/stv0g/gose:amd64-v{{ .Major }}.{{ .Minor }}"

  use: buildx
  dockerfile: Dockerfile.release

  goos: linux
  goarch: amd64
  
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"

- id: arm64
  image_templates: 
  - "ghcr.io/stv0g/gose:arm64-{{ .Tag }}"
  - "ghcr.io/stv0g/gose:arm64-v{{ .Major }}"
  - "ghcr.io/stv0g/gose:arm64-v{{ .Major }}.{{ .Minor }}"

  use: buildx
  dockerfile: Dockerfile.release

  goos: linux
  goarch: arm64
  
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"

- id: arm
  image_templates: 
  - "ghcr.io/stv0g/gose:arm-{{ .Tag }}"
  - "ghcr.io/stv0g/gose:arm-v{{ .Major }}"
  - "ghcr.io/stv0g/gose:arm-v{{ .Major }}.{{ .Minor }}"

  use: buildx
  dockerfile: Dockerfile.release

  goos: linux
  goarch: arm
  goarm: "7"
  
  build_flag_templates:
  - "--platform=linux/arm/v7"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
- name_template: "ghcr.io/stv0g/{{ .ProjectName }}:{{ .Tag }}"
  image_templates:
  - "ghcr.io/stv0g/gose:arm-{{ .Tag }}"
  - "ghcr.io/stv0g/gose:arm64-{{ .Tag }}"
  - "ghcr.io/stv0g/gose:amd64-{{ .Tag }}"
- name_template: "ghcr.io/stv0g/{{ .ProjectName }}:latest"
  image_templates:
  - "ghcr.io/stv0g/gose:arm-{{ .Tag }}"
  - "ghcr.io/stv0g/gose:arm64-{{ .Tag }}"
  - "ghcr.io/stv0g/gose:amd64-{{ .Tag }}"
