# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

FROM alpine:3.21

RUN apk update && apk add ca-certificates curl && rm -rf /var/cache/apk/*

ENV GIN_MODE=release

EXPOSE 8080/tcp

HEALTHCHECK --interval=30s --timeout=30s --retries=3 \
    CMD curl -f http://localhost:8080/api/v1/healthz

COPY gose /

ENTRYPOINT ["/gose"]
