# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

name: Goreleaser

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all tags
      run: git fetch --force --tags

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        check-latest: true
        go-version-file: go.mod

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Set up QEmu User Static
      uses: dbhi/qus/action@main
      with:
        targets: arm aarch64

    - name: Log in to the Container registry
      uses: docker/login-action@a5609cb39f57be157c39b77359abfaa43aeaeb8f
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
